-- Table: public.items
-- DROP TABLE public.items;
CREATE TABLE public.items (
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    item_name character varying COLLATE pg_catalog."default" NOT NULL,
    item_price numeric(10, 2) NOT NULL DEFAULT 1.0,
    item_title text COLLATE pg_catalog."default" NOT NULL DEFAULT 'long(er) product title/name'::text,
    item_about text [] COLLATE pg_catalog."default" NOT NULL DEFAULT '{"this is a great product","it looks great"}'::text [],
    item_description text COLLATE pg_catalog."default" NOT NULL DEFAULT 'This is a product, etc., etc.'::text
) TABLESPACE pg_default;
ALTER TABLE public.items OWNER to "amazinAdmin";
COMMENT ON TABLE public.items IS 'Items table. This should hold most of the item data needed for the site.';
COMMENT ON COLUMN public.items.item_id IS 'items ids';
COMMENT ON COLUMN public.items.item_name IS 'This is the item name. should not be too long.';
COMMENT ON COLUMN public.items.item_about IS 'about item sections';
COMMENT ON COLUMN public.items.item_description IS 'for Product description section';